apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

  
resources:
- ./base/000-namespace.yaml
- ./base/010-app-config-map.yaml
- ./base/020-rbac.yaml
- ./base/030-dc.yaml
#- ./base/040-svc.yaml
- ./base/045-svc-nodeport-ingress.yaml
- ./base/050-ingress.yaml


