apiVersion: v1
kind: ConfigMap
metadata:
  name: publisher
  namespace: bomc-publish-namespace
data:
  application-k8s.properties: |-
    bomc.consumer=http://bomc-replace.me
    bomc.github=https://bomc-replace.me
