apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: publish
  name: publisher
  namespace: default
data:
  application-prod.properties: |-
    bomc.consumer=http://bomc-replace.me
    bomc.github=https://bomc-replace.me
