apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: publish
  name: publisher
  namespace: default
data:
  application-prod.properties: |-
    bomc.consumer=http://OVERRIDE_BY_OVERLAYS
    bomc.github=https://OVERRIDE_BY_OVERLAYS
