apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: publish
  name: publisher
  namespace: bomc-rename-namespace
data:
  application-k8s.properties: |-
    bomc.consumer=http://bomc-replace.me
    bomc.github=https://bomc-replace.me
