---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: publish
  namespace: bomc-rename-namespace
  name: pod-reader-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","configmaps"]
    verbs: ["get","watch","list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: publish
  name: publisher-role-binding
  namespace: bomc-rename-namespace
subjects:
  - kind: ServiceAccount
    name: publisher-account
    namespace: bomc-rename-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader-role

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: publish
  name: publisher-account
  namespace: bomc-rename-namespace

