apiVersion: v1
kind: Service
metadata:
  name: publish-service-nodeport-ingress
  namespace: default
  labels:
    app: publish
spec:
  selector:
    app: publish
  ports:
  - protocol: TCP
    name: 8181-tcp
    port: 8181
    targetPort: 8181
  type: NodePort
