apiVersion: v1
kind: ConfigMap
metadata:
  name: publisher
  namespace: default
data:
  application-prod.properties: |-
    bomc.consumer=http://consumer-service.bomc-consumer-prod.svc.cluster.local:8081
    bomc.github=https://api.github.com
