apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-consumer-pod
        image: curlimages/curl:7.75.0
        command: ["/bin/sh", "-c"]
        args: ["while [ $(curl --connect-timeout 5 --no-keepalive -s -v -w '%{http_code}\n' -H 'Connection: close' http://consumer-service.bomc-consumer.svc.cluster.local:8081/actuator/health/liveness -o /dev/null) -ne 200 ]; do sleep 5; echo `date +'%d.%m.%Y %H:%M:%S'` - Waiting for consumer pod... ; done"]
